str = "i am a coder"
str.endswith("er")
str.capitalize()
str.replace("a", "A")
str.split()
str.find("a")
str.count("a")

print(str)
print(str.endswith("er"))
print(str.capitalize())
print(str.replace("a", "A"))
print(str.split())
print(str.find("a"))
print(str.count("a"))
